line-length = 100
indent-width = 4

target-version = "py313"
exclude = ["*venv*", ".git", "build", "dist"]

[lint]
preview = true
select = ["ALL"]

ignore = ["D100", "D104", "D203", "D212", "DOC201", "DOC501", "CPY001", "PLR6301"]

[format]
preview = true
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 100

[lint.isort]
known-local-folder = ["src"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[lint.per-file-ignores]
"tests/**" = ["ANN001", "ANN201", "D101", "D102", "D103", "S101"]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.flake8-annotations]
mypy-init-return = true
