[environment]
python-version = "3.13"

[[overrides]]
include = ["src/core/initializer.py"]

[overrides.rules]
missing-argument = "warn"

[[overrides]]
include = ["tests/*"]

[overrides.rules]
unresolved-attribute = "warn"
